# Generated by Django 6.0.5 on 2026-05-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_jobcategory_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('recruiter', 'Recruiter'), ('jobseeker', 'Job Seeker')], max_length=15),
        ),
    ]
